version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pet_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - backend

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: pet_frontend_app
    restart: always
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://api:8081
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: pet_postgres
    restart: always
    environment:
      POSTGRES_DB: pet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
